// Metronome
let metroId=null, beatIndex=0;
const bpm=document.getElementById('bpm');
const meter=document.getElementById('meter');
const beatUnit=document.getElementById('beatUnit');
function meterParts(){const parts=(meter.value||'4|4').split('|');return {beats:Number(parts[0])||4,denom:Number(parts[1])||4};}
function currentBeatUnitLabel(){const map={'4':'Quarter note','8':'Eighth note','2':'Half note','dotted4':'Dotted quarter'};return map[beatUnit.value]||'Quarter note';}
function beatIntervalMs(){const base=60000/Number(bpm.value);if(beatUnit.value==='8')return base/2;if(beatUnit.value==='2')return base*2;if(beatUnit.value==='dotted4')return base*1.5;return base;}
function rebuildBeatIndicators(){const n=meterParts().beats,box=document.getElementById('beatIndicators');box.innerHTML='';for(let i=0;i<n;i++){const s=document.createElement('span');if(i===beatIndex)s.classList.add('on');box.appendChild(s);}}
function tick(){const n=meterParts().beats;clickTone(beatIndex===0);document.getElementById('beatDot').textContent=beatIndex+1;document.getElementById('beatDot').classList.add('flash');setTimeout(()=>document.getElementById('beatDot').classList.remove('flash'),70);rebuildBeatIndicators();beatIndex=(beatIndex+1)%n;}
function stopMetro(){if(metroId)clearInterval(metroId);metroId=null;beatIndex=0;rebuildBeatIndicators();document.getElementById('metroBtn').textContent='Start';document.getElementById('beatDot').textContent='1';}
function startMetro(){stopMetro();tick();metroId=setInterval(tick,beatIntervalMs());document.getElementById('metroBtn').textContent='Stop';}
function refreshMetro(){document.getElementById('bpmText').textContent=bpm.value;beatIndex=0;rebuildBeatIndicators();const tip=document.querySelector('#metro .tip');if(tip){const mp=meterParts();tip.innerHTML=`Current setup: <b>${mp.beats}/${mp.denom}</b> • beat = <b>${currentBeatUnitLabel()}</b>. For beginners, try 60–80 BPM.`;}if(metroId)startMetro();}
document.getElementById('metroBtn').addEventListener('click',()=>metroId?stopMetro():startMetro());bpm.addEventListener('input',refreshMetro);meter.addEventListener('change',refreshMetro);beatUnit.addEventListener('change',refreshMetro);document.getElementById('minusBpm').addEventListener('click',()=>{bpm.value=Math.max(40,Number(bpm.value)-5);refreshMetro();});document.getElementById('plusBpm').addEventListener('click',()=>{bpm.value=Math.min(200,Number(bpm.value)+5);refreshMetro();});refreshMetro();

const rhythms={simple:['TA • TA • TA • TA','TA • TA • TI-TI • TA','TA • TI-TI • TA • TA','TI-TI • TI-TI • TA • TA','TA • SHH • TA • TA'],moderate:['TA • TI-TI • TI-TI • TA','TI-TI • TA • SHH • TI-TI','TA • TA-A • TI-TI • TA','TI-TI • TI-TI • TI-TI • TA','TA • SHH • TI-TI • TA-A']};
document.getElementById('newRhythm').addEventListener('click',()=>{const list=rhythms[document.getElementById('rhythmLevel').value];document.getElementById('rhythmText').textContent=list[Math.floor(Math.random()*list.length)];});

if(!document.getElementById('vocalPattern')){
  const vocalPanel=document.getElementById('vocal');
  const headTitle=vocalPanel?.querySelector('h2');if(headTitle)headTitle.textContent='🎤 Vocal Warm-up Studio';
  const headText=vocalPanel?.querySelector('.toolhead p');if(headText)headText.textContent='Teacher-controlled pitch patterns for breathing, pitch matching, resonance and agility.';
  const box=vocalPanel?.querySelector('.box');
  if(box)box.innerHTML=`<div class="vocal-control-grid"><label>Pattern<select id="vocalPattern"><option value="12321">1–2–3–2–1 • Pitch Match</option><option value="five">1–2–3–4–5–4–3–2–1 • 5-Note Scale</option><option value="13531">1–3–5–3–1 • Arpeggio</option><option value="1358531">1–3–5–8–5–3–1 • Range Connection</option><option value="agility">1–2–3–4–3–2–1 • Agility</option><option value="chromatic">1–♭2–2–♭2–1 • Semitone Control</option></select></label><label>Exercise sound<select id="vocalSyllable"><option>Ah</option><option>Ee</option><option>Oo</option><option>Hum</option><option>Lip Trill</option><option>Nay</option></select></label><label>Tempo<div class="tempo-control"><input id="vocalTempo" max="140" min="50" type="range" value="76"><span id="vocalTempoText">76 BPM</span></div></label></div><div class="pattern" id="warmPattern">1 – 2 – 3 – 2 – 1</div><div class="warm-goal" id="warmGoal">Goal: easy pitch matching and steady tone.</div><div class="controls" style="justify-content:center"><button class="btn" id="stepDownWarm">−½ Step</button><button class="btn" id="pitchRef">▶ Starting Note</button><button class="btn primary" id="playWarm">▶ Play Pattern</button><button class="btn" id="stepUpWarm">+½ Step</button><button class="btn" id="newWarm">Next Pattern</button></div><div class="readout" id="warmReadout">Starting note: C4 • Sing on “Ah”</div><div class="tip">Teacher tip: keep the pattern in a comfortable range. For ages 5–8, use short patterns and playful sounds such as Hum or Lip Trill. For ages 9–14, introduce 5-note scales, arpeggios and gentle agility patterns.</div>`;
  const st=document.createElement('style');st.textContent='.vocal-control-grid{display:grid;grid-template-columns:1.35fr 1fr 1.15fr;gap:10px;margin:0 auto 16px;max-width:880px;text-align:left}.vocal-control-grid label{font-size:12px;font-weight:750;color:#667085;display:flex;flex-direction:column;gap:6px}.vocal-control-grid select{width:100%}.tempo-control{display:flex;align-items:center;gap:9px;min-height:39px}.tempo-control input{flex:1;min-width:90px}.tempo-control span{white-space:nowrap;color:#252a34;font-weight:800;font-size:12px}.warm-goal{margin:8px auto 15px;max-width:760px;padding:9px 12px;border-radius:12px;background:#f2f0ff;color:#5147c9;font-size:13px;font-weight:750}@media(max-width:800px){.vocal-control-grid{grid-template-columns:1fr}}';document.head.appendChild(st);
}
const vocalPatterns={'12321':{label:'1 – 2 – 3 – 2 – 1',notes:[0,2,4,2,0],goal:'Goal: easy pitch matching and steady tone.'},'five':{label:'1 – 2 – 3 – 4 – 5 – 4 – 3 – 2 – 1',notes:[0,2,4,5,7,5,4,2,0],goal:'Goal: smooth five-note scale and even breath.'},'13531':{label:'1 – 3 – 5 – 3 – 1',notes:[0,4,7,4,0],goal:'Goal: tune the major arpeggio and keep the tone connected.'},'1358531':{label:'1 – 3 – 5 – 8 – 5 – 3 – 1',notes:[0,4,7,12,7,4,0],goal:'Goal: connect the range gently without pushing.'},'agility':{label:'1 – 2 – 3 – 4 – 3 – 2 – 1',notes:[0,2,4,5,4,2,0],goal:'Goal: light vocal agility with clear note changes.'},'chromatic':{label:'1 – ♭2 – 2 – ♭2 – 1',notes:[0,1,2,1,0],goal:'Goal: hear and control small semitone movement.'}};
const vocalPatternOrder=['12321','five','13531','1358531','agility','chromatic'];let currentPattern='12321';
function startMidi(){const name=document.getElementById('startNote').value;const semis={'C':0,'C#':1,'D':2,'D#':3,'E':4,'F':5,'F#':6,'G':7,'G#':8,'A':9,'A#':10,'B':11};return 60+semis[name];}
function setStartFromMidi(midi){const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];const wrapped=((midi-60)%12+12)%12;document.getElementById('startNote').value=names[wrapped];}
function refreshWarm(){const sel=document.getElementById('vocalPattern');currentPattern=sel?sel.value:currentPattern;const p=vocalPatterns[currentPattern]||vocalPatterns['12321'];const syllable=document.getElementById('vocalSyllable')?.value||'Ah';const tempo=document.getElementById('vocalTempo')?.value||76;document.getElementById('warmPattern').textContent=p.label;document.getElementById('warmGoal').textContent=p.goal;document.getElementById('warmReadout').textContent='Starting note: '+labelForMidi(startMidi())+' • Sing on “'+syllable+'”';const tempoText=document.getElementById('vocalTempoText');if(tempoText)tempoText.textContent=tempo+' BPM';}
document.getElementById('startNote').addEventListener('change',refreshWarm);document.getElementById('vocalPattern').addEventListener('change',refreshWarm);document.getElementById('vocalSyllable').addEventListener('change',refreshWarm);document.getElementById('vocalTempo').addEventListener('input',refreshWarm);document.getElementById('newWarm').addEventListener('click',()=>{const idx=vocalPatternOrder.indexOf(currentPattern);currentPattern=vocalPatternOrder[(idx+1)%vocalPatternOrder.length];document.getElementById('vocalPattern').value=currentPattern;refreshWarm();});document.getElementById('stepUpWarm').addEventListener('click',()=>{setStartFromMidi(startMidi()+1);refreshWarm();});document.getElementById('stepDownWarm').addEventListener('click',()=>{setStartFromMidi(startMidi()-1);refreshWarm();});document.getElementById('pitchRef').addEventListener('click',()=>pianoTone(startMidi(),0.72,2.0));document.getElementById('playWarm').addEventListener('click',()=>{const base=startMidi();const p=vocalPatterns[currentPattern]||vocalPatterns['12321'];const bpmValue=Number(document.getElementById('vocalTempo').value)||76;const spacing=Math.max(300,Math.round((60000/bpmValue)*0.72));p.notes.forEach((off,i)=>setTimeout(()=>pianoTone(base+off,0.64,1.15),i*spacing));});refreshWarm();

const promptSets={'5–8':['Find C, then play the next white key.','Clap four steady beats with the teacher.','Sing one comfortable note and copy the teacher.','Play or sing three notes going upward.','Listen to two notes. Point to the higher one.','Copy a short clap pattern: clap – clap – rest – clap.'],'9–14':['Play a 5-note pattern and keep it steady with the metronome.','Teacher plays two notes. Identify whether the second is higher or lower.','Sing 1–2–3–2–1, then move the starting pitch up one semitone.','Clap a 4-beat rhythm, then repeat it with a stronger beat 1.','Play C–E–G, then identify the sound as a three-note chord shape.','Create a two-bar rhythm using TA, TI-TI and one rest.']};
document.getElementById('newPrompt').addEventListener('click',()=>{const list=promptSets[ageSel.value]||promptSets['5–8'];document.getElementById('promptText').textContent=list[Math.floor(Math.random()*list.length)];});

const staffSvg=document.getElementById('staffSvg'),staffLines=document.getElementById('staffLines'),ledgerLines=document.getElementById('ledgerLines'),noteGraphic=document.getElementById('noteGraphic'),clefLabel=document.getElementById('clefLabel'),notationClef=document.getElementById('notationClef'),notationLevel=document.getElementById('notationLevel'),notationMode=document.getElementById('notationMode');let notationMidi=60,notationAnswer='C4',notationCanPlay=true;
function svgEl(name,attrs={}){const el=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el;}
function drawStaff(){staffLines.innerHTML='';for(let i=0;i<5;i++)staffLines.appendChild(svgEl('line',{x1:125,x2:820,y1:95+i*22,y2:95+i*22,stroke:'#4b5563','stroke-width':2}));}drawStaff();
const pitchMap={treble:{basic:[['C4',60,205],['D4',62,194],['E4',64,183],['F4',65,172],['G4',67,161]],intermediate:[['C4',60,205],['D4',62,194],['E4',64,183],['F4',65,172],['G4',67,161],['A4',69,150],['B4',71,139],['C5',72,128]],advanced:[['B3',59,216],['C4',60,205],['D4',62,194],['E4',64,183],['F4',65,172],['G4',67,161],['A4',69,150],['B4',71,139],['C5',72,128],['D5',74,117],['E5',76,106]]},bass:{basic:[['C3',48,205],['D3',50,194],['E3',52,183],['F3',53,172],['G3',55,161]],intermediate:[['C3',48,205],['D3',50,194],['E3',52,183],['F3',53,172],['G3',55,161],['A3',57,150],['B3',59,139],['C4',60,128]],advanced:[['B2',47,216],['C3',48,205],['D3',50,194],['E3',52,183],['F3',53,172],['G3',55,161],['A3',57,150],['B3',59,139],['C4',60,128],['D4',62,117],['E4',64,106]]}};
const accidentalSets={basic:[['C♯4',61,'♯'],['E♭4',63,'♭'],['F♯4',66,'♯']],intermediate:[['C♯4',61,'♯'],['D♯4',63,'♯'],['E♭4',63,'♭'],['F♯4',66,'♯'],['B♭4',70,'♭']],advanced:[['C♯4',61,'♯'],['D♭4',61,'♭'],['D♯4',63,'♯'],['E♭4',63,'♭'],['F♯4',66,'♯'],['G♭4',66,'♭'],['G♯4',68,'♯'],['A♭4',68,'♭'],['B♭4',70,'♭']]};
const restSets={basic:[['Quarter Rest','𝄽'],['Half Rest','𝄼']],intermediate:[['Whole Rest','𝄻'],['Half Rest','𝄼'],['Quarter Rest','𝄽'],['Eighth Rest','𝄾']],advanced:[['Whole Rest','𝄻'],['Half Rest','𝄼'],['Quarter Rest','𝄽'],['Eighth Rest','𝄾'],['Sixteenth Rest','𝄿']]};
const intervalSets={basic:[['2nd',60,62],['3rd',60,64]],intermediate:[['2nd',60,62],['3rd',60,64],['4th',60,65],['5th',60,67]],advanced:[['2nd',60,62],['3rd',60,64],['4th',60,65],['5th',60,67],['6th',60,69],['Octave',60,72]]};
const chordSets={basic:[['C major','C'],['A minor','Am']],intermediate:[['C major','C'],['A minor','Am'],['G major','G'],['D minor','Dm']],advanced:[['C major','C'],['A minor','Am'],['G major','G'],['D minor','Dm'],['F major','F'],['E minor','Em'],['C7','C7']]};
function clearNotation(){ledgerLines.innerHTML='';noteGraphic.innerHTML='';clefLabel.textContent=notationClef.value==='treble'?'Treble Clef':'Bass Clef';}
function drawSingleNote(name,midi,y,acc=''){const x=470;if(y>183){for(let ly=205;ly<=y+2;ly+=22)ledgerLines.appendChild(svgEl('line',{x1:x-32,x2:x+32,y1:ly,y2:ly,stroke:'#4b5563','stroke-width':2}));}const e=svgEl('ellipse',{cx:x,cy:y,rx:15,ry:10,transform:`rotate(-18 ${x} ${y})`,fill:'#252a34'});const stem=svgEl('line',{x1:x+13,x2:x+13,y1:y,y2:y-68,stroke:'#252a34','stroke-width':4});noteGraphic.appendChild(e);noteGraphic.appendChild(stem);if(acc){const t=svgEl('text',{x:x-55,y:y+8,'font-size':34,'font-weight':700,fill:'#252a34'});t.textContent=acc;noteGraphic.appendChild(t);}notationMidi=midi;notationAnswer=name;notationCanPlay=true;}
function renderNotation(){clearNotation();const level=notationLevel.value,mode=notationMode.value,help=document.getElementById('notationModeHelp'),playBtn=document.getElementById('notationPlay');notationCanPlay=true;if(mode==='notes'){const pool=pitchMap[notationClef.value][level],e=pool[Math.floor(Math.random()*pool.length)];drawSingleNote(e[0],e[1],e[2]);help.textContent='Staff-note recognition.';}else if(mode==='accidentals'){const pool=accidentalSets[level],e=pool[Math.floor(Math.random()*pool.length)];drawSingleNote(e[0],e[1],161,e[2]);help.textContent='Name the written pitch including the sharp or flat.';}else if(mode==='rests'){const pool=restSets[level],e=pool[Math.floor(Math.random()*pool.length)],t=svgEl('text',{x:430,y:175,'font-size':82,'font-weight':700,fill:'#252a34'});t.textContent=e[1];noteGraphic.appendChild(t);notationAnswer=e[0];notationCanPlay=false;help.textContent='Identify the rest symbol and discuss its value.';}else if(mode==='intervals'){const pool=intervalSets[level],e=pool[Math.floor(Math.random()*pool.length)],ys=[183,183-(e[2]-e[1])*5.5];[0,1].forEach(i=>{const x=410+i*115,y=ys[i];noteGraphic.appendChild(svgEl('ellipse',{cx:x,cy:y,rx:15,ry:10,transform:`rotate(-18 ${x} ${y})`,fill:'#252a34'}));noteGraphic.appendChild(svgEl('line',{x1:x+13,x2:x+13,y1:y,y2:y-62,stroke:'#252a34','stroke-width':4}));});notationAnswer=e[0];notationMidi=e[1];notationCanPlay=true;window.__notationInterval=[e[1],e[2]];help.textContent='Name the interval between the two notes.';}else{const pool=chordSets[level],e=pool[Math.floor(Math.random()*pool.length)],t=svgEl('text',{x:410,y:175,'font-size':72,'font-weight':850,fill:'#252a34'});t.textContent=e[1];noteGraphic.appendChild(t);notationAnswer=e[0];notationCanPlay=false;help.textContent='Read the chord symbol and name the chord.';}playBtn.disabled=!notationCanPlay&&mode!=='intervals';playBtn.textContent=mode==='intervals'?'▶ Hear Interval':'▶ Hear Note';document.getElementById('notationHint').textContent='Look at the notation. Ask the student to answer.';}
document.getElementById('notationNext').addEventListener('click',renderNotation);notationClef.addEventListener('change',renderNotation);notationLevel.addEventListener('change',renderNotation);notationMode.addEventListener('change',renderNotation);document.getElementById('notationReveal').addEventListener('click',()=>document.getElementById('notationHint').textContent='Answer: '+notationAnswer+'.');document.getElementById('notationPlay').addEventListener('click',()=>{if(notationMode.value==='intervals'&&window.__notationInterval){window.__notationInterval.forEach((m,i)=>setTimeout(()=>pianoTone(m,.75,1.5),i*800));}else if(notationCanPlay)pianoTone(notationMidi,.8,2.1);});renderNotation();

const canvas=document.getElementById('whiteboardCanvas'),bctx=canvas.getContext('2d');let drawing=false,boardColor='#20242c',erasing=false,boardHistory=[],boardReady=false;
function boardSize(){const wrap=canvas.parentElement;return {w:Math.max(320,wrap.clientWidth||900),h:window.innerHeight>800?520:430};}
function drawBoardBackground(){const {w,h}=boardSize();bctx.save();bctx.fillStyle='#fff';bctx.fillRect(0,0,w,h);if(document.getElementById('boardTemplate').value==='staff'){bctx.strokeStyle='#4b5563';bctx.lineWidth=2;for(let g=0;g<4;g++){const top=45+g*Math.max(90,(h-90)/4);for(let i=0;i<5;i++){bctx.beginPath();bctx.moveTo(30,top+i*13);bctx.lineTo(w-30,top+i*13);bctx.stroke();}}}bctx.restore();}
function initWhiteboard(preserve=true){const wrap=canvas.parentElement;if(!wrap||wrap.clientWidth<20)return;const old=(preserve&&boardReady)?canvas.toDataURL('image/png'):null,{w,h}=boardSize(),dpr=Math.max(1,window.devicePixelRatio||1);canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);bctx.setTransform(dpr,0,0,dpr,0,0);bctx.lineCap='round';bctx.lineJoin='round';drawBoardBackground();boardReady=true;if(old){const img=new Image();img.onload=()=>bctx.drawImage(img,0,0,w,h);img.src=old;}}
function saveBoard(){if(!boardReady)return;if(boardHistory.length>=20)boardHistory.shift();boardHistory.push(canvas.toDataURL('image/png'));}
function pt(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{if(!boardReady)initWhiteboard(false);if(!boardReady)return;e.preventDefault();drawing=true;saveBoard();try{canvas.setPointerCapture(e.pointerId)}catch(_){}const p=pt(e);bctx.beginPath();bctx.moveTo(p.x,p.y);bctx.lineTo(p.x+.01,p.y+.01);bctx.strokeStyle=erasing?'#fff':boardColor;bctx.lineWidth=erasing?Number(document.getElementById('brushSize').value)*3:Number(document.getElementById('brushSize').value);bctx.stroke();});
canvas.addEventListener('pointermove',e=>{if(!drawing||!boardReady)return;e.preventDefault();const p=pt(e);bctx.strokeStyle=erasing?'#fff':boardColor;bctx.lineWidth=erasing?Number(document.getElementById('brushSize').value)*3:Number(document.getElementById('brushSize').value);bctx.lineTo(p.x,p.y);bctx.stroke();});function endBoard(){drawing=false;try{bctx.closePath()}catch(_){}}canvas.addEventListener('pointerup',endBoard);canvas.addEventListener('pointercancel',endBoard);
document.querySelectorAll('.color-dot').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.color-dot').forEach(x=>x.classList.remove('active'));b.classList.add('active');boardColor=b.dataset.color;erasing=false;document.getElementById('eraserBtn').textContent='Eraser';}));document.getElementById('eraserBtn').addEventListener('click',()=>{erasing=!erasing;document.getElementById('eraserBtn').textContent=erasing?'Eraser On':'Eraser';});document.getElementById('clearBoard').addEventListener('click',()=>{if(!boardReady)initWhiteboard(false);saveBoard();drawBoardBackground();});document.getElementById('boardTemplate').addEventListener('change',()=>{if(!boardReady)initWhiteboard(false);saveBoard();drawBoardBackground();});document.getElementById('undoBoard').addEventListener('click',()=>{if(!boardHistory.length)return;const last=boardHistory.pop(),{w,h}=boardSize(),img=new Image();img.onload=()=>{drawBoardBackground();bctx.drawImage(img,0,0,w,h)};img.src=last;});navs.forEach(b=>{if(b.dataset.tool==='whiteboard')b.addEventListener('click',()=>setTimeout(()=>initWhiteboard(boardReady),50));});window.addEventListener('resize',()=>{if(document.getElementById('whiteboard').classList.contains('active')){clearTimeout(window.__wbTimer);window.__wbTimer=setTimeout(()=>initWhiteboard(true),120);}});